[tool.poetry]
name = "venv"
version = "0.1.0"
description = ""
authors = ["keyhong <wnhong96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
acryl-datahub = {version = "0.12.1.5", extras = ["mariadb"]}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
